### ISSUE TITLE
String de XmlEnviado difere do XmlEnviado

### ISSUE THREAD

**Issue by Laranjeiras** [dfebr/dfebr-net#9]
No método RetornoProcessamento da classe ServAutorzTemplate, ao gerar o XmlEnviado está atribuindo valores diferentes do Xml que realmente foi enviado.

Atual:
var xmlEnviado = Utils.ObterStringXML(enviNFe.NFe);

Como eu acho que deveria estar:
var xmlEnviado = Utils.ObterStringXML(enviNFe);

**Comment by DSBRBrasil** [comment]
> No método RetornoProcessamento da classe ServAutorzTemplate, ao gerar o XmlEnviado está atribuindo valores diferentes do Xml que realmente foi enviado.
> 
> Atual:
> var xmlEnviado = Utils.ObterStringXML(enviNFe.NFe);
> 
> Como eu acho que deveria estar:
> var xmlEnviado = Utils.ObterStringXML(enviNFe);

Ainda não ficou claro .... onde esta o erro ?

**Comment by paulinhoamc** [comment]
@Laranjeiras 
Depende do conteúdo que vc deseja receber de volta, se enviar para a classe o enviNFe, vc receberá de retorno o arquivo xml no formato string de texto com a tag pai "enviNFe", caso envie apenas o objeto enviNFe.NFe (enviando para a classe de conversão o objeto filho chamado NFe), será retornado uma string de texto do arquivo xml com a tag pai "NFe", ignorando as classes irmãs à NFe.

**Comment by Laranjeiras** [comment]
Estou me referindo sobre o preenchimento da classe RetAutorz, propriedade XmlEnvio, no método ServAutorzTemplate.RetornoProcessamento
O preenchimento está diferente do que realmente está sendo enviado. Essa propriedade não interfere na autorização, mas no meu caso uso para Log.

Se executarmos o comando
![image](https://user-images.githubusercontent.com/6052106/70878697-42416880-1fa1-11ea-90a8-bb17cecdf05e.png)

Resultado ...
```
<ArrayOfNFe>
	<NFe>
		<infNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00" 
```

Se executarmos o comando:
![image](https://user-images.githubusercontent.com/6052106/70878748-7ae14200-1fa1-11ea-9347-699fe91b9110.png)

Resultado...
```
<enviNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
	<idLote>
		1
	</idLote>
	<indSinc>
		1
	</indSinc>
	<NFe>
		<infNFe versao="4.00" ```


Esse segundo comando sim está de acordo com os Schemas de NFe.

Caso ainda persista a duvida mando um PR para que possamos avaliar a mudança.

**Comment by DSBRBrasil** [comment]
Essa função tem o objetivo de transformar uma string Xml em um objeto .... O objetivo desse comando no contexto do método ServAutorzTemplate.RetornoProcessamento é retornar apenas a NFe.
Espero que eu tenha entendido corretamente

**Comment by Laranjeiras** [comment]
A função que eu citei transforma a classe em uma string e na conversão está convertendo errado, irei submeter um PR.

**Comment by DSBRBrasil** [comment]
> Estou me referindo sobre o preenchimento da classe RetAutorz, propriedade XmlEnvio, no método ServAutorzTemplate.RetornoProcessamento
> O preenchimento está diferente do que realmente está sendo enviado. Essa propriedade não interfere na autorização, mas no meu caso uso para Log.
> 
> Se executarmos o comando
> ![image](https://user-images.githubusercontent.com/6052106/70878697-42416880-1fa1-11ea-90a8-bb17cecdf05e.png)
> 
> Resultado ...
> 
> ```
> <ArrayOfNFe>
> 	<NFe>
> 		<infNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00" 
> ```
> 
> Se executarmos o comando:
> ![image](https://user-images.githubusercontent.com/6052106/70878748-7ae14200-1fa1-11ea-9347-699fe91b9110.png)
> 
> Resultado...
> 
> ```
> <enviNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
> 	<idLote>
> 		1
> 	</idLote>
> 	<indSinc>
> 		1
> 	</indSinc>
> 	<NFe>
> 		<infNFe versao="4.00" ```
> 
> 
> Esse segundo comando sim está de acordo com os Schemas de NFe.
> 
> Caso ainda persista a duvida mando um PR para que possamos avaliar a mudança.
> ```

Opa.... ja verifcou a questão do envio em lote ? dai seria uma coleção de NFe... estou correto ?

**Comment by DSBRBrasil** [comment]
Ok
